4-th sem/DB_sql_C#_postgre_BlogApp/blogDBApp/blogDBApp/Models/publications.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace blogDBApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class publications
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public publications()
        {
            this.comments = new HashSet<comments>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string text { get; set; }
        public int rating { get; set; }
        public System.DateTime date { get; set; }
        public int user { get; set; }
        public int theme { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comments> comments { get; set; }
        public virtual themes themes { get; set; }
        public virtual users users { get; set; }
    }
}

4-th sem/DB_sql_C#_postgre_BlogApp/blogDBApp/blogDBApp/Controllers/publicationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using blogDBApp.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;

namespace blogDBApp.Controllers
{
    public class publicationsController : Controller
    {
        private blogDataBaseEntities2 db = new blogDataBaseEntities2();

        // GET: publications
        public ActionResult Index()
        {
            var publications = db.publications.Include(p => p.themes).Include(p => p.users);
            return View(publications.ToList());
        }

        public ActionResult FilterByTheme(int? id)
        {
            ViewBag.publications = db.publications.
              Include(p => p.themes).
              Where(p => p.theme == id).
              ToList();
            ViewBag.theme = "Theme: " + db.themes.Find(id).name;
            ViewBag.themeId = id;
            return View();
        }

        public ActionResult Search()
        {
            return View();
        }

        public ActionResult SearchResult(string title, string theme, string text, string user, DateTime? minDate, DateTime? maxDate, int? minRating)
        {
            ViewBag.date = DateTime.Now;
            ViewBag.publications = db.publications.
                Where(p => p.users.name.ToLower().Trim().Contains(user.ToLower().Trim())).
                Where(p => p.name.ToLower().Trim().Contains(title.ToLower().Trim())).
                Where(p => p.text.ToLower().Trim().Contains(text.ToLower().Trim())).
                Where(p => p.rating >= minRating).
                Where(p => p.themes.name.ToLower().Trim().Contains(theme.ToLower().Trim())).
                Where(p => p.date >= minDate && p.date <= maxDate).
                ToList();
            return View();

        }


        // GET: publications/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            publications publications = db.publications.Find(id);
            if (publications == null)
            {
                return HttpNotFound();
            }
            return View(publications);
        }

        // GET: publications/Create
        [Authorize]
        public ActionResult Create()
        {
            ViewBag.theme = new SelectList(db.themes, "id", "name");
            ViewBag.user = new SelectList(db.users, "id", "name");
            return View();
        }

        [Authorize]
        public ActionResult AddNew(int? id)
        {
            ViewBag.date = DateTime.Now;
            ViewBag.theme = id;
            ViewBag.user = db.users.Where(u => u.name == HttpContext.User.Identity.Name).ToList()[0].id;
            return View();
        }

        // POST: publications/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Create([Bind(Include = "id,name,text,rating,date,user,theme")] publications publications)
        {
            if (ModelState.IsValid)
            {
                db.publications.Add(publications);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.theme = new SelectList(db.themes, "id", "name", publications.theme);
            ViewBag.user = new SelectList(db.users, "id", "name", publications.user);
            return View(publications);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult AddNew([Bind(Include = "id,name,text,rating,date,user,theme")] publications publications, int? id)
        {
            if (ModelState.IsValid)
            {
                db.publications.Add(publications);
                db.SaveChanges();
                return RedirectToAction("Index","themes");
            }

            ViewBag.theme = id;
            ViewBag.user = db.users.Where(u => u.name == HttpContext.User.Identity.Name).ToList()[0].id;
            return View(publications);
        }

        // GET: publications/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            publications publications = db.publications.Find(id);
            if (publications == null)
            {
                return HttpNotFound();
            }
            ViewBag.theme = new SelectList(db.themes, "id", "name", publications.theme);
            ViewBag.user = new SelectList(db.users, "id", "name", publications.user);
            return View(publications);
        }

        // POST: publications/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Edit([Bind(Include = "id,name,text,rating,date,user,theme")] publications publications)
        {
            if (ModelState.IsValid)
            {
                db.Entry(publications).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.theme = new SelectList(db.themes, "id", "name", publications.theme);
            ViewBag.user = new SelectList(db.users, "id", "name", publications.user);
            return View(publications);
        }

        // GET: publications/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            publications publications = db.publications.Find(id);
            if (publications == null)
            {
                return HttpNotFound();
            }
            return View(publications);
        }

        // POST: publications/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult DeleteConfirmed(int id)
        {
            publications publications = db.publications.Find(id);
            db.publications.Remove(publications);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

4-th sem/DB_sql_C#_postgre_BlogApp/blogDBApp/blogDBApp/Controllers/usersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using blogDBApp.Models;

namespace blogDBApp.Controllers
{
    public class usersController : Controller
    {
        private blogDataBaseEntities2 db = new blogDataBaseEntities2();

        public ActionResult Search()
        {
            return View();
        }

        public ActionResult SearchResult(string name, string mail, string text, bool? moderate)
        {
            ViewBag.users = db.users.
             Where(p => p.name.ToLower().Trim().Contains(name.ToLower().Trim())).
             Where(p => p.mail.ToLower().Trim().Contains(mail.ToLower().Trim())).
             Where(p => p.about.ToLower().Trim().Contains(text.ToLower().Trim())).
             Where(p => p.isModer == moderate).
             ToList();
            return View(ViewBag);

        }

        // GET: users
        public ActionResult Index()
        {
            return View(db.users.ToList());
        }

        // GET: users/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            users users = db.users.Find(id);
            if (users == null)
            {
                return HttpNotFound();
            }
            return View(users);
        }

        // GET: users/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: users/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,name,mail,about,isModer")] users users)
        {
            if (ModelState.IsValid)
            {
                db.users.Add(users);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(users);
        }

        // GET: users/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            users users = db.users.Find(id);
            if (users == null)
            {
                return HttpNotFound();
            }
            return View(users);
        }

        // POST: users/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Edit([Bind(Include = "id,name,mail,about,isModer")] users users)
        {
            if (ModelState.IsValid)
            {
                
                db.Entry(users).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(users);
        }

        // GET: users/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            users users = db.users.Find(id);
            if (users == null)
            {
                return HttpNotFound();
            }
            return View(users);
        }

        // POST: users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            users users = db.users.Find(id);
            db.users.Remove(users);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

4-th sem/DB_sql_C#_postgre_BlogApp/blogDBApp/blogDBApp/Views/publications/AddNew.cshtml
@model blogDBApp.Models.publications

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>publications</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.text, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.text, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.text, "", new { @class = "text-danger" })
        </div>
    </div>


    <input type="hidden" value="0" name="rating" />

    
    <input type="hidden" name="date" value="@ViewBag.date" />

    <input type="hidden" value="@ViewBag.user" name="user" />

    <input type="hidden" value="@ViewBag.theme" name="theme" />

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to publications", "FilterByTheme", new { id = ViewBag.theme },null)
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

4-th sem/DB_sql_C#_postgre_BlogApp/blogDBApp/blogDBApp/Views/publications/Create.cshtml
@model blogDBApp.Models.publications

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>publications</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.text, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.text, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.text, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.rating, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.rating, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.rating, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.user, "user", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("user", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.user, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.theme, "theme", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("theme", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.theme, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

4-th sem/DB_sql_C#_postgre_BlogApp/blogDBApp/blogDBApp/Views/publications/Delete.cshtml
@model blogDBApp.Models.publications

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>publications</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.text)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.text)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.rating)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.rating)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.themes.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.themes.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.users.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.users.name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

4-th sem/DB_sql_C#_postgre_BlogApp/blogDBApp/blogDBApp/Views/publications/Details.cshtml
@model blogDBApp.Models.publications

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>publications</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.text)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.text)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.rating)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.rating)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.themes.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.themes.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.users.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.users.name)
        </dd>

    </dl>
</div>

4-th sem/DB_sql_C#_postgre_BlogApp/blogDBApp/blogDBApp/Views/publications/Edit.cshtml
@model blogDBApp.Models.publications

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>publications</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.text, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.text, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.text, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.rating, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.rating, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.rating, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.user, "user", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("user", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.user, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.theme, "theme", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("theme", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.theme, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

4-th sem/DB_sql_C#_postgre_BlogApp/blogDBApp/blogDBApp/Views/publications/FilterByTheme.cshtml
<h1>@Html.Raw((string)ViewBag.theme)</h1>


<h2>
    @Html.ActionLink("Create", "AddNew", "publications", new { id = ViewBag.themeId }, null)
</h2>

<table class="table">
    <tr>
        <td>
            <h4>Publication title</h4>
        </td>
        <td>
            <h4>Date</h4>
        </td>
        <td>
            <h4>User</h4>
        </td>
        <td>
            <h4>Rating</h4>
        </td>
    </tr>
    @foreach (var item in ViewBag.publications)
    {
        <tr>
            <td>
                @Html.ActionLink((string)item.name, "FilterByPublication", "comments", new { id = item.id }, null)
            </td>
            <td>
                @Html.Raw((DateTime)item.date)
            </td>
            <td>
                @Html.ActionLink((string)item.users.name,"Details", "users", new { id = item.users.id}, null)
            </td>
            <td>
                @Html.Raw((int)item.rating)
            </td>
        </tr>
    }
</table>

4-th sem/DB_sql_C#_postgre_BlogApp/blogDBApp/blogDBApp/Views/publications/Index.cshtml
@model IEnumerable<blogDBApp.Models.publications>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.text)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.rating)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.themes.name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.users.name)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.text)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.rating)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.date)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.themes.name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.users.name)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.id }) |
            @Html.ActionLink("Details", "Details", new { id=item.id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.id })
        </td>
    </tr>
}

</table>

4-th sem/DB_sql_C#_postgre_BlogApp/blogDBApp/blogDBApp/Views/publications/Search.cshtml
@using (Html.BeginForm("SearchResult", "publications", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div class="form-group">
        <div class="col-md-10">
            <label for="query">
                <h4>Title</h4><input type="text" name="title" class="form-control" />
            </label>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-10">
            <label for="query">
                <h4>Text</h4><input type="text" name="text" class="form-control" />
            </label>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-10">
            <label for="query">
                <h4>User name</h4><input type="text" name="user" class="form-control" />
            </label>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-10">
            <label for="query">
                <h4>Min rating</h4><input type="number" name="minRating" value="0"class="form-control" />
            </label>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-10">
            <label for="query">
                <h4>Min date</h4><input type="date" name="minDate" value="1800-03-23"class="form-control" />
            </label>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-10">
            <label for="query">
                <h4>Max date</h4><input type="date" name="maxDate" value="2800-03-23"class="form-control" />
            </label>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-10">
            <label for="query">
                <h4>Theme</h4><input type="text" name="theme" class="form-control" />
            </label>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-10">
            <input type="submit" value="Search" class="btn btn-default" />
        </div>
    </div>
}

4-th sem/DB_sql_C#_postgre_BlogApp/blogDBApp/blogDBApp/Views/publications/SearchResult.cshtml
<table class="table">
    <tr>
        <td>
            <h4>Publication title</h4>
        </td>
        <td>
            <h4>Date</h4>
        </td>
        <td>
            <h4>User</h4>
        </td>
        <td>
            <h4>Rating</h4>
        </td>
        <td>
            <h4>
                Theme
            </h4>
        </td>
    </tr>
    @foreach (var item in ViewBag.publications)
    {
    <tr>
        <td>
            @Html.ActionLink((string)item.name, "FilterByPublication", "comments", new { id = item.id }, null)
        </td>
        <td>
            @Html.Raw((DateTime)item.date)
        </td>
        <td>
            @Html.ActionLink((string)item.users.name, "Details", "users", new { id = item.id }, null)
        </td>
        <td>
            @item.rating
        </td>
        <td>
            @item.themes.name
        </td>
    </tr>
    }
</table>