4-th sem/DB_sql_C#_postgre_BlogApp/blogDBApp/blogDBApp/Models/messages.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace blogDBApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class messages
    {
        public int id { get; set; }
        public int sender { get; set; }
        public int receiver { get; set; }
        public string name { get; set; }
        public System.DateTime date { get; set; }
        public string text { get; set; }
    
        public virtual users users { get; set; }
        public virtual users users1 { get; set; }
    }
}

4-th sem/DB_sql_C#_postgre_BlogApp/blogDBApp/blogDBApp/Controllers/messagesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using blogDBApp.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;


namespace blogDBApp.Controllers
{
    public class messagesController : Controller
    {
        private blogDataBaseEntities2 db = new blogDataBaseEntities2();
        // GET: messages
        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            var messages = db.messages.Include(m => m.users).Include(m => m.users1);
            return View(messages.ToList());
        }


        [Authorize(Roles = "Admin")]
        public ActionResult Search()
        {
            return View();
        }

        [Authorize(Roles = "Admin")]
        public ActionResult SearchResult(string senderName, string recName, string title, DateTime? minDate, DateTime? maxDate, string text)
        {
            ViewBag.messages = db.messages.
                Where(m => m.users.name.ToLower().Trim().Contains(senderName.ToLower().Trim())).
                Where(m => m.users1.name.ToLower().Trim().Contains(recName.ToLower().Trim())).
                Where(m => m.name.ToLower().Trim().Contains(title.ToLower().Trim())).
                Where(m => m.date >= minDate && m.date <= maxDate).
                Where(m => m.text.ToLower().Trim().Contains(text.ToLower().Trim())).
                ToList();
            return View();
        }

        [Authorize]
        public ActionResult FilterByUser()
        {

            string loggedUserName = HttpContext.User.Identity.Name;
            int loggedUserID = db.users.Where(u => u.name == loggedUserName).ToList()[0].id;
            ViewBag.resieved = db.messages.
                Where(m => m.receiver == loggedUserID).
                ToList();

            ViewBag.sended = db.messages.
                Where(m => m.sender == loggedUserID).
                ToList();

            return View();
        }

        // GET: messages/Details/5
        [Authorize]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            messages messages = db.messages.Find(id);
            if (messages == null)
            {
                return HttpNotFound();
            }
            return View(messages);
        }

        // GET: messages/Create
        [Authorize]
        public ActionResult Create()
        {
            ViewBag.receiver = new SelectList(db.users, "id", "name");
            ViewBag.sender = new SelectList(db.users, "id", "name");
            return View();
        }

        // POST: messages/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Create([Bind(Include = "id,sender,receiver,name,date,text")] messages messages)
        {
            if (ModelState.IsValid)
            {
                db.messages.Add(messages);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.receiver = new SelectList(db.users, "id", "name", messages.receiver);
            ViewBag.sender = new SelectList(db.users, "id", "name", messages.sender);
            return View(messages);
        }

        [Authorize]
        public ActionResult Send()
        {
            ViewBag.date = DateTime.Now;
            string loggedUserName = HttpContext.User.Identity.Name;
            int loggedUserID = db.users.Where(u => u.name == loggedUserName).ToList()[0].id;
            ViewBag.receiver = new SelectList(db.users, "id", "name");
            ViewBag.sender = loggedUserID;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Send([Bind(Include = "id,sender,receiver,name,date,text")] messages messages)
        {
            ViewBag.date = DateTime.Now;
            string loggedUserName = HttpContext.User.Identity.Name;
            int loggedUserID = db.users.Where(u => u.name == loggedUserName).ToList()[0].id;

            if (ModelState.IsValid)
            {
                db.messages.Add(messages);
                db.SaveChanges();
                return RedirectToAction("FilterByUser");
            }

            ViewBag.receiver = new SelectList(db.users, "id", "name", messages.receiver);
            ViewBag.sender = loggedUserID;
            return View(messages);
        }

        // GET: messages/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            messages messages = db.messages.Find(id);
            if (messages == null)
            {
                return HttpNotFound();
            }
            ViewBag.receiver = new SelectList(db.users, "id", "name", messages.receiver);
            ViewBag.sender = new SelectList(db.users, "id", "name", messages.sender);
            return View(messages);
        }

        // POST: messages/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit([Bind(Include = "id,sender,receiver,name,date,text")] messages messages)
        {
            if (ModelState.IsValid)
            {
                db.Entry(messages).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.receiver = new SelectList(db.users, "id", "name", messages.receiver);
            ViewBag.sender = new SelectList(db.users, "id", "name", messages.sender);
            return View(messages);
        }

        // GET: messages/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            messages messages = db.messages.Find(id);
            if (messages == null)
            {
                return HttpNotFound();
            }
            return View(messages);
        }

        // POST: messages/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult DeleteConfirmed(int id)
        {
            messages messages = db.messages.Find(id);
            db.messages.Remove(messages);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

4-th sem/DB_sql_C#_postgre_BlogApp/blogDBApp/blogDBApp/Controllers/usersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using blogDBApp.Models;

namespace blogDBApp.Controllers
{
    public class usersController : Controller
    {
        private blogDataBaseEntities2 db = new blogDataBaseEntities2();

        public ActionResult Search()
        {
            return View();
        }

        public ActionResult SearchResult(string name, string mail, string text, bool? moderate)
        {
            ViewBag.users = db.users.
             Where(p => p.name.ToLower().Trim().Contains(name.ToLower().Trim())).
             Where(p => p.mail.ToLower().Trim().Contains(mail.ToLower().Trim())).
             Where(p => p.about.ToLower().Trim().Contains(text.ToLower().Trim())).
             Where(p => p.isModer == moderate).
             ToList();
            return View(ViewBag);

        }

        // GET: users
        public ActionResult Index()
        {
            return View(db.users.ToList());
        }

        // GET: users/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            users users = db.users.Find(id);
            if (users == null)
            {
                return HttpNotFound();
            }
            return View(users);
        }

        // GET: users/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: users/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,name,mail,about,isModer")] users users)
        {
            if (ModelState.IsValid)
            {
                db.users.Add(users);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(users);
        }

        // GET: users/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            users users = db.users.Find(id);
            if (users == null)
            {
                return HttpNotFound();
            }
            return View(users);
        }

        // POST: users/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Edit([Bind(Include = "id,name,mail,about,isModer")] users users)
        {
            if (ModelState.IsValid)
            {
                
                db.Entry(users).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(users);
        }

        // GET: users/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            users users = db.users.Find(id);
            if (users == null)
            {
                return HttpNotFound();
            }
            return View(users);
        }

        // POST: users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            users users = db.users.Find(id);
            db.users.Remove(users);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

4-th sem/DB_sql_C#_postgre_BlogApp/blogDBApp/blogDBApp/Views/messages/Create.cshtml
@model blogDBApp.Models.messages

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>messages</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.sender, "sender", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("sender", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.sender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.receiver, "receiver", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("receiver", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.receiver, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.text, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.text, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.text, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

4-th sem/DB_sql_C#_postgre_BlogApp/blogDBApp/blogDBApp/Views/messages/Delete.cshtml
@model blogDBApp.Models.messages

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>messages</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.text)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.text)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.users.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.users.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.users1.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.users1.name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

4-th sem/DB_sql_C#_postgre_BlogApp/blogDBApp/blogDBApp/Views/messages/Details.cshtml
@model blogDBApp.Models.messages

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>messages</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.text)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.text)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.users.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.users.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.users1.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.users1.name)
        </dd>

    </dl>
</div>

4-th sem/DB_sql_C#_postgre_BlogApp/blogDBApp/blogDBApp/Views/messages/Edit.cshtml
@model blogDBApp.Models.messages

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>messages</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.sender, "sender", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("sender", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.sender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.receiver, "receiver", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("receiver", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.receiver, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.text, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.text, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.text, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

4-th sem/DB_sql_C#_postgre_BlogApp/blogDBApp/blogDBApp/Views/messages/FilterByUser.cshtml
@{
    ViewBag.Title = "Messages";
}


<h1>
    @Html.ActionLink("Send new message", "Send")
</h1>

<h2>Resieved</h2>

<table class="table">
    <tr>
        <th>
            <h3>Message Title</h3>
        </th>
        <th>
            <h3>Date</h3>
        </th>
        <th>
            <h3>Message Text</h3>
        </th>
        <th>
            <h3>Reciever</h3>
        </th>
        <th>
            <h3>Sender</h3>
        </th>
        <th><h3>CRUD</h3></th>
        <th></th>
    </tr>

    @foreach (var item in ViewBag.resieved)
    {
        <tr>
            <td>
                @item.name
            </td>
            <td>
                @item.date
            </td>
            <td>
                @item.text
            </td>
            <td>
                @item.users.name
            </td>
            <td>
                @item.users1.name
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.id }) |
                @Html.ActionLink("Details", "Details", new { id = item.id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.id })
            </td>
        </tr>
    }

</table>


<h2>Sended</h2>


<table class="table">
    <tr>
        <th>
            <h3>Message Title</h3>
        </th>
        <th>
            <h3>Date</h3>
        </th>
        <th>
            <h3>Message Text</h3>
        </th>
        <th>
            <h3>Reciever</h3>
        </th>
        <th>
            <h3>Sender</h3>
        </th>
        <th><h3>CRUD</h3></th>
        <th></th>
    </tr>

    @foreach (var item in ViewBag.sended)
    {
        <tr>
            <td>
                @item.name
            </td>
            <td>
                @item.date
            </td>
            <td>
                @item.text
            </td>
            <td>
                @item.users.name
            </td>
            <td>
                @item.users1.name
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.id }) |
                @Html.ActionLink("Details", "Details", new { id = item.id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.id })
            </td>
        </tr>
    }

</table>

4-th sem/DB_sql_C#_postgre_BlogApp/blogDBApp/blogDBApp/Views/messages/Index.cshtml
@model IEnumerable<blogDBApp.Models.messages>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            <h3>Message Title</h3>
        </th>
        <th>
            <h3>Date</h3>
        </th>
        <th>
            <h3>Message Text</h3>
        </th>
        <th>
           <h3>Reciever</h3>
        </th>
        <th>
            <h3>Sender</h3>
        </th>
        <th><h3>CRUD</h3></th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.date)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.text)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.users.name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.users1.name)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.id }) |
            @Html.ActionLink("Details", "Details", new { id=item.id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.id })
        </td>
    </tr>
}

</table>

4-th sem/DB_sql_C#_postgre_BlogApp/blogDBApp/blogDBApp/Views/messages/Search.cshtml
@using (Html.BeginForm("SearchResult", "messages", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div class="form-group">
        <div class="col-md-10">
            <label for="query">
                <h4>Sender name</h4> <input type="text" name="senderName" class="form-control" />
            </label>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-10">
            <label for="query">
                <h4>Reciever name</h4> <input type="text" name="recName" class="form-control" />
            </label>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-10">
            <label for="query">
                <h4>Message title</h4> <input type="text" name="title" class="form-control" />
            </label>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-10">
            <label for="query">
                <h4>Message text</h4> <input type="text" name="text" class="form-control" />
            </label>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-10">
            <label for="query">
                <h4>Min date</h4><input type="date" name="minDate" value="1800-03-23" class="form-control" />
            </label>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-10">
            <label for="query">
                <h4>Max date</h4><input type="date" name="maxDate" value="2800-03-23" class="form-control" />
            </label>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-10">
            <input type="submit" value="Search" class="btn btn-default" />
        </div>
    </div>
}

4-th sem/DB_sql_C#_postgre_BlogApp/blogDBApp/blogDBApp/Views/messages/SearchResult.cshtml
<table class="table">
    <tr>
        <td>
            <h4>Message title</h4>
        </td>
        <td>
            <h4>Sender</h4>
        </td>
        <td>
            <h4>Reciever</h4>
        </td>
        <td>
            <h4>Date</h4>
        </td>
        <td>
            <h4>
                Message text
            </h4>
        </td>
    </tr>
    @foreach (var item in ViewBag.messages)
    {
        <tr>
            <td>
                @Html.ActionLink((string)item.name, "Details", "messages", new { id = item.id }, null)
            </td>
            <td>
                @Html.ActionLink((string)item.users.name, "Details", "users", new { id = item.users.id}, null)
            </td>
            <td>
                @Html.ActionLink((string)item.users1.name, "Details", "users", new { id = item.users1.id }, null)
            </td>
            <td>
                @item.date
            </td>
            <td>
                @item.text
            </td>
        </tr>
    }
</table>

4-th sem/DB_sql_C#_postgre_BlogApp/blogDBApp/blogDBApp/Views/messages/Send.cshtml
@model blogDBApp.Models.messages

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>messages</h4>

        <input type="hidden" value ="@ViewBag.sender" name = "sender"/>

        <div class="form-group">
            @Html.LabelFor(model => model.receiver, "receiver", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("receiver", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.receiver, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <input type="hidden" name="date" value="@ViewBag.date" />

        <div class="form-group">
            @Html.LabelFor(model => model.text, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.text, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.text, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Send" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Message box", "FilterByUser", "messages", new { id = ViewBag.sender }, null)
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}