4-th sem/DB_sql_C#_postgre_BlogApp/blogDBApp/blogDBApp/Controllers/themesListController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using blogDBApp.Models;
using Npgsql;

namespace blogDBApp.Controllers
{
    public class themesListController : Controller
    {

        private blogDataBaseEntities2 db = new blogDataBaseEntities2();

        // GET: thmesList
        public ActionResult themesList()
        {
            return View(db.themes.ToList());
        }

        
        public ActionResult themePublications(int? id)
        {
            ViewBag.publications = db.publications.
                Include(p => p.themes).
                Where(p => p.theme == id).
                ToList();
            ViewBag.theme = "Theme: " + db.themes.Find(id).name;
            return View(ViewBag);
        }

        public ActionResult publicationComments(int? id)
        {
            ViewBag.comments = db.comments.
                Include(c => c.publications).
                Where(c => c.publication == id).
                ToList();
            ViewBag.publicationName = db.publications.Find(id).name;
            ViewBag.publicationText = db.publications.Find(id).text;
            ViewBag.publicationRating = db.publications.Find(id).rating;
            ViewBag.publicationDate = db.publications.Find(id).date;

            return View(ViewBag);
        }
    }
}

4-th sem/DB_sql_C#_postgre_BlogApp/blogDBApp/blogDBApp/Views/themesList/publicationComments.cshtml
<table class="table1">
<h1>@Html.Raw((string)ViewBag.publicationName)</h1>
<h4>@Html.Raw((DateTime)ViewBag.publicationDate)</h4>
<h4>@Html.Raw((string)ViewBag.publicationText)</h4>
<h4>@Html.Raw("Rating: " + (int)ViewBag.publicationRating)</h4>

<table class="table">
    <tr>
    </tr>
    @foreach (var item in ViewBag.comments)
    {
        <tr>
            <td>UserName</td>
            <td>
                @Html.Raw((string)item.text)
            </td>
            <td>
                @Html.Raw("Rating: " + (int)item.rating)
            </td>
        </tr>
    }
</table>

4-th sem/DB_sql_C#_postgre_BlogApp/blogDBApp/blogDBApp/Views/themesList/themePublications.cshtml
<h1>@Html.Raw((string)ViewBag.theme)</h1>


<table class="table">
    <tr>
        <td>
            <h4>Name</h4>
        </td>
        <td>
            <h4>Date</h4>
        </td>
        <td>
            <h4>Rating</h4>
        </td>
    </tr>
    @foreach (var item in ViewBag.publications)
    {
        <tr>
            <td>
                @Html.ActionLink((string)item.name, "publicationComments", "themesList", new { id = item.id }, null)
            </td>
            <td>
                @Html.Raw((DateTime)item.date)
            </td>
            <td>
                @Html.Raw((int)item.rating)
            </td>
        </tr>
    }
</table>

4-th sem/DB_sql_C#_postgre_BlogApp/blogDBApp/blogDBApp/Views/themesList/themesList.cshtml
@model IEnumerable<blogDBApp.Models.themes>

@{
    ViewBag.Title = "Themes";
}

<h4>Themes</h4>

<table class="table">
   
    @foreach (var item in Model)
    {
    <tr>
        <td>
           @Html.ActionLink(item.name, "themePublications", "themesList", new { id = item.id }, null)
        </td>
    </tr>
    }
</table>