4-th sem/DB_sql_C#_postgre_BlogApp/blogDBApp/blogDBApp/Controllers/commentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using blogDBApp.Models;

namespace blogDBApp.Controllers
{
    public class commentsController : Controller
    {
        private blogDataBaseEntities2 db = new blogDataBaseEntities2();

        public ActionResult Search()
        {
            return View();
        }

        public ActionResult SearchResult(string text, string user, string publication, int? rating, DateTime? dateMin, DateTime? dateMax)
        {
            ViewBag.comments = db.comments.
                 Where(p => p.text.ToLower().Trim().Contains(text.ToLower().Trim())).
                 Where(p => p.users.name.ToLower().Trim().Contains(user.ToLower().Trim())).
                 Where(p => p.publications.name.ToLower().Trim().Contains(publication.ToLower().Trim())).
                 Where(p => p.rating >= rating).
                 Where(p => p.date >= dateMin && p.date <= dateMax).
                 ToList();
            return View(ViewBag);

        }

        // GET: comments
        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            var comments = db.comments.Include(c => c.publications).Include(c => c.users);
            return View(comments.ToList());
        }

        public ActionResult FilterByPublication(int? id)
        {
            ViewBag.comments = db.comments.
                Include(c => c.users).
                Where(c => c.publication == id).
                ToList();

            var p = db.publications.Find(id);
            ViewBag.publicationName = p.name;
            ViewBag.publicationText = p.text;
            ViewBag.publicationRating = p.rating;
            ViewBag.publicationDate = p.date;
            int pUserID = db.publications.Find(id).user;
            ViewBag.publicationUser = db.users.Find(pUserID).name;
            ViewBag.publicationID = id;

            return View();
        }

        // GET: comments/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            comments comments = db.comments.Find(id);
            if (comments == null)
            {
                return HttpNotFound();
            }
            return View(comments);
        }

        // GET: comments/Create
        [Authorize]
        public ActionResult Create()
        {
            ViewBag.publication = new SelectList(db.publications, "id", "name");
            ViewBag.user = new SelectList(db.users, "id", "name");
            return View();
        }



        [Authorize]
        public ActionResult AddNew(int? id)
        {
            ViewBag.date = DateTime.Now;
            ViewBag.publication = id;
            ViewBag.user =db.users.Where(u => u.name == HttpContext.User.Identity.Name).ToList()[0].id;
            return View();
        }

        // POST: comments/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Create([Bind(Include = "C_id,text,rating,date,publication,user")] comments comments)
        {
            if (ModelState.IsValid)
            {
                db.comments.Add(comments);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.publication = new SelectList(db.publications, "id", "name", comments.publication);
            ViewBag.user = new SelectList(db.users, "id", "name", comments.user);
            return View(comments);
        }




        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult AddNew([Bind(Include = "C_id,text,rating,date,publication,user")] comments comments, int? id)
        {
            if (ModelState.IsValid)
            {
                db.comments.Add(comments);
                db.SaveChanges();
                return RedirectToAction("Index","themes");
            }

            ViewBag.publication = id;
            ViewBag.user = db.users.Where(u => u.name == HttpContext.User.Identity.Name).ToList()[0].id;
            return View(comments);
        }



        // GET: comments/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            comments comments = db.comments.Find(id);
            if (comments == null)
            {
                return HttpNotFound();
            }
            ViewBag.publication = new SelectList(db.publications, "id", "name", comments.publication);
            ViewBag.user = new SelectList(db.users, "id", "name", comments.user);
            return View(comments);
        }

        // POST: comments/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Edit([Bind(Include = "C_id,text,rating,date,publication,user")] comments comments)
        {
            if (ModelState.IsValid)
            {
                db.Entry(comments).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.publication = new SelectList(db.publications, "id", "name", comments.publication);
            ViewBag.user = new SelectList(db.users, "id", "name", comments.user);
            return View(comments);
        }

        // GET: comments/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            comments comments = db.comments.Find(id);
            if (comments == null)
            {
                return HttpNotFound();
            }
            return View(comments);
        }

        // POST: comments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult DeleteConfirmed(int id)
        {
            comments comments = db.comments.Find(id);
            db.comments.Remove(comments);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

4-th sem/DB_sql_C#_postgre_BlogApp/blogDBApp/blogDBApp/Controllers/usersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using blogDBApp.Models;

namespace blogDBApp.Controllers
{
    public class usersController : Controller
    {
        private blogDataBaseEntities2 db = new blogDataBaseEntities2();

        public ActionResult Search()
        {
            return View();
        }

        public ActionResult SearchResult(string name, string mail, string text, bool? moderate)
        {
            ViewBag.users = db.users.
             Where(p => p.name.ToLower().Trim().Contains(name.ToLower().Trim())).
             Where(p => p.mail.ToLower().Trim().Contains(mail.ToLower().Trim())).
             Where(p => p.about.ToLower().Trim().Contains(text.ToLower().Trim())).
             Where(p => p.isModer == moderate).
             ToList();
            return View(ViewBag);

        }

        // GET: users
        public ActionResult Index()
        {
            return View(db.users.ToList());
        }

        // GET: users/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            users users = db.users.Find(id);
            if (users == null)
            {
                return HttpNotFound();
            }
            return View(users);
        }

        // GET: users/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: users/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,name,mail,about,isModer")] users users)
        {
            if (ModelState.IsValid)
            {
                db.users.Add(users);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(users);
        }

        // GET: users/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            users users = db.users.Find(id);
            if (users == null)
            {
                return HttpNotFound();
            }
            return View(users);
        }

        // POST: users/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Edit([Bind(Include = "id,name,mail,about,isModer")] users users)
        {
            if (ModelState.IsValid)
            {
                
                db.Entry(users).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(users);
        }

        // GET: users/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            users users = db.users.Find(id);
            if (users == null)
            {
                return HttpNotFound();
            }
            return View(users);
        }

        // POST: users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            users users = db.users.Find(id);
            db.users.Remove(users);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

4-th sem/DB_sql_C#_postgre_BlogApp/blogDBApp/blogDBApp/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

4-th sem/DB_sql_C#_postgre_BlogApp/blogDBApp/blogDBApp/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    OMSK<br />
    OmSTU<br />
    <abbr title="Phone">P:</abbr>
    89048262301
</address>

<address>
    <strong>Mail:</strong>   <a href="mailto:zaicev9797@gmail.com">zaicev9797@gmail.com</a><br />
</address>

4-th sem/DB_sql_C#_postgre_BlogApp/blogDBApp/blogDBApp/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

4-th sem/DB_sql_C#_postgre_BlogApp/blogDBApp/blogDBApp/Views/Home/Request1.cshtml
<table class="table">
    <tr>
        <td>
            <h3>authror</h3>
        </td>
        <td>
            <h3>
                rating
            </h3>
        </td>
        <td>
            <h3>
                text
            </h3>
        </td>
    </tr>

    @foreach (var item in ViewBag.result)
    {
        <tr>
            <td>
                @Html.ActionLink((string)item.name, "Details", "users", new { id = item.id }, null)
            </td>
            <td>
                @item.rating
            </td>
            <td>
                @item.text
            </td>
        </tr>

    }
</table>

4-th sem/DB_sql_C#_postgre_BlogApp/blogDBApp/blogDBApp/Views/Home/Request10.cshtml
<table class="table">
    <tr>
        <td>
            <h3>user</h3>
        </td>
    </tr>

    @foreach (var item in ViewBag.result)
    {
        <tr>
            <td>
                @Html.ActionLink((string)item.name, "Details", "users", new { id = item.id }, null)
            </td>
        </tr>
    }
</table>

4-th sem/DB_sql_C#_postgre_BlogApp/blogDBApp/blogDBApp/Views/Home/Request2.cshtml
<table class="table">
    <tr>
        <td>
            <h3>authror</h3>
        </td>
        <td>
            <h3>
                text
            </h3>
        </td>
        <td>
            <h3>
                date
            </h3>
        </td>
    </tr>

    @foreach (var item in ViewBag.result)
    {
        <tr>
            <td>
                @Html.ActionLink((string)item.name, "Details", "users", new { id = item.id }, null)
            </td>
            <td>
                @item.text
            </td>
            <td>
                @item.date
        </tr>

    }
</table>

4-th sem/DB_sql_C#_postgre_BlogApp/blogDBApp/blogDBApp/Views/Home/Request3.cshtml
<table class="table">
    <tr>
        <td>
            <h3>
                publication
            </h3>
        </td>
        <td>
            <h3>
                comments count
            </h3>
        </td>
    </tr>

    @foreach (var item in ViewBag.result)
    {
        <tr>
            <td>
                @Html.ActionLink((string)item.name + " ", "FilterByPublicaation", "comments", new { id = item.id }, null)
            </td>
            <td>
                @item.count
            </td>
        </tr>

    }
</table>

4-th sem/DB_sql_C#_postgre_BlogApp/blogDBApp/blogDBApp/Views/Home/Request4.cshtml
<table class="table">
    <tr>
        <td>
            <h3>User</h3>
        </td>
        <td>
            <h3>Publicatoin</h3>
        </td>
        <td>
            <h3>Theme</h3>
        </td>
    </tr>

    @foreach (var item in ViewBag.result)
    {
    <tr>
        <td>
            @Html.ActionLink((string)item.uName, "Details", "users", new { id = item.uID }, null)
        </td>

        <td>
            @Html.ActionLink((string)item.pName, "FilterByPublication", "comments", new { id = item.pID }, null)
        </td>
        <td>
            @Html.ActionLink((string)item.tName, "FilterByTheme", "publications", new { id = item.tID }, null)
        </td>
    </tr>

    }
</table>

4-th sem/DB_sql_C#_postgre_BlogApp/blogDBApp/blogDBApp/Views/Home/Request5.cshtml
<table class="table">
    <tr>
        <td>
            <h3>user</h3>
        </td>
        <td>
            <h3>
                publication
            </h3>
        </td>
        <td>
            <h3>
                theme
            </h3>
        </td>
    </tr>

    @foreach (var item in ViewBag.result)
    {
        <tr>
            <td>
                @Html.ActionLink((string)item.uName, "Details", "users", new { id = item.uID }, null)
            </td>
            <td>
                @Html.ActionLink((string)item.pName, "FilterByPublication", "comments", new { id = item.pID }, null)
            </td>
            <td>
                @Html.ActionLink((string)item.tName, "FilterByTheme", "publications", new { id = item.tID }, null)
            </td>
        </tr>
    }
</table>

4-th sem/DB_sql_C#_postgre_BlogApp/blogDBApp/blogDBApp/Views/Home/Request6.cshtml
<table class="table">
    <tr>
        <td>
            <h3>comment</h3>
        </td>
        <td>
            <h3>user</h3>
        </td>
        <td>
            <h3>
                publication
            </h3>
        </td>
        <td>
            <h3>
                theme
            </h3>
        </td>
        <td>
            <h3>
                rating
            </h3>
        </td>
    </tr>

    @foreach (var item in ViewBag.result)
    {
        <tr>
            <td>
                @item.cText
            </td>
            <td>
                @Html.ActionLink((string)item.uName, "Details", "users", new { id = item.uID }, null)
            </td>
            <td>
                @Html.ActionLink((string)item.pName, "FilterByPublication", "comments", new { id = item.pID }, null)
            </td>
            <td>
                @Html.ActionLink((string)item.tName, "FilterByTheme", "publications", new { id = item.tID }, null)
            </td>
            <td>
                @item.cRating
            </td>
        </tr>
    }
</table>

4-th sem/DB_sql_C#_postgre_BlogApp/blogDBApp/blogDBApp/Views/Home/Request7.cshtml
<table class="table">
    <tr>
        <td>
            <h3>user</h3>
        </td>
        <td>
            <h3>
                comment
            </h3>
        </td>
        <td>
            <h3>
                type
            </h3>
        </td>
    </tr>

    @foreach (var item in ViewBag.result)
    {
        <tr>
            <td>
                @item.name
            </td>
            <td>
                @item.text
            </td>
            <td>
                @item.type
            </td>
        </tr>
    }
</table>

4-th sem/DB_sql_C#_postgre_BlogApp/blogDBApp/blogDBApp/Views/Home/Request8.cshtml
<table class="table">
    <tr>
        <td>
            <h3>theme</h3>
        </td>
        <td>
            <h3>
                avg
            </h3>
        </td>
        <td>
            <h3>
                max
            </h3>
        </td>
    </tr>

    @foreach (var item in ViewBag.result)
    {
        <tr>
            <td>
                @Html.ActionLink((string)item.name, "FilterByTheme", "publications", new { id = item.id }, null)
            </td>
            <td>
                @item.avg
            </td>
            <td>
                @item.max
            </td>
        </tr>
    }
</table>

4-th sem/DB_sql_C#_postgre_BlogApp/blogDBApp/blogDBApp/Views/Home/Request9.cshtml
<table class="table">
    <tr>
        <td>
            <h3>theme</h3>
        </td>
        <td>
            <h3>
                avg
            </h3>
        </td>
    </tr>

    @foreach (var item in ViewBag.result)
    {
        <tr>
            <td>
                @Html.ActionLink((string)item.name, "FilterByTheme", "publications", new { id = item.id }, null)
            </td>
            <td>
                @item.avg
            </td>
        </tr>
    }
</table>

4-th sem/DB_sql_C#_postgre_BlogApp/blogDBApp/blogDBApp/Views/Home/Requests.cshtml
<table class="table">
    <tr>
        @using (Html.BeginForm("Request1", "home", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            <td>
                <div class="form-group">
                    <div class="col-md-10">
                            <label for="name">Show comments with not 0 rating of user: </label>
                            <input type="text" name="name" class="form-control" />
                    </div>
                </div>
            </td>
            <td>
                <div class="form-group">
                    <div class="col-md-10">
                        <input type="submit" value="Request1" class="btn btn-default" />
                    </div>
                </div>
            </td>
        }
    </tr>
    <tr>
        @using (Html.BeginForm("Request2", "home", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            <div class="form-group">
                <td>
                    <div class="col-md-10">
                        <label for="request2">Show all comments added after latest post</label>
                    
                </td>
                <td>
                    <div class="col-md-10">
                        <input type="submit" value="Request2" name="request2" class="btn btn-default" />
                    </div>
                </td>
                
            </div>
        }
    </tr>

    <hr />
    <tr>
        @using (Html.BeginForm("Request3", "home", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            <div class="form-group">

                <td>
                    <div class="col-md-10">
                        <label for="request3">Show count of comments for each publication</label>
                    </div>
                </td>
                <td>
                    <div class="col-md-10">
                        <input type="submit" value="Request3" name="request3" class="btn btn-default" />
                    </div>
                </td>
            </div>
        }
    </tr>

    <hr />
    <tr>
        @using (Html.BeginForm("Request4", "home", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            <td>
                <div class="form-group">
                    <div class="col-md-10">
                            <label for="theme">Show users who create publications on theme:</label>
                            <input type="text" name="theme" class="form-control" />
                    </div>
                </div>
            </td>
            <td>
                <div class="form-group">
                    <div class="col-md-10">
                        <input type="submit" value="Request4" class="btn btn-default" />
                    </div>
                </div>
            </td>
        }
    </tr>
    <tr>
        @using (Html.BeginForm("Request5", "home", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            <td>
                <div class="form-group">
                    <div class="col-md-10">
                            <label for="theme1">Show users who create publications on theme1:</label>
                            <input type="text" name="theme1" class="form-control" />
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-10">
                            <label for="theme2">theme2:</label>
                            <input type="text" name="theme2" class="form-control" />
                    </div>
                </div>
            </td>
            <td>
                <div class="form-group">
                    <div class="col-md-10">
                        <input type="submit" value="Request5" class="btn btn-default" />
                    </div>
                </div>
            </td>
            }
    </tr>
    <tr>
        @using (Html.BeginForm("Request6", "home", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            <td>
                <div class="form-group">
                    <div class="col-md-10">
                            <label for="theme1">Show users who create publications on theme1:</label>
                            <input type="text" name="theme1" class="form-control" />
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-10">
                            <label for="theme2">theme2:</label>
                            <input type="text" name="theme2" class="form-control" />
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-10">
                            <label for="rating">and it's rating not lower then:</label>
                            <input type="number" name="rating" class="form-control" />
                    </div>
                </div>
            </td>
            <td>
                <div class="form-group">
                    <div class="col-md-10">
                        <input type="submit" value="Request6" class="btn btn-default" />
                    </div>
                </div>
            </td>
            }
    </tr>
    <tr>
        @using (Html.BeginForm("Request7", "home", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            <div class="form-group">
                
                <td>
                    <div class="col-md-10">
                        <label for="request7">Show bad guys</label>
                    </div>
                </td>
                <td>
                    <div class="col-md-10">
                        <input type="submit" value="Request7" name="request7" class="btn btn-default" />
                    </div>
                </td>
            </div>
        }
    </tr>
    <tr>
        @using (Html.BeginForm("Request8", "home", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            <div class="form-group">
               
                <td>
                    <div class="col-md-10">
                        <label for="request8">Show average and maximum length of the comments for each theme</label>
                    </div>
                </td>
                <td>
                    <div class="col-md-10">
                        <input type="submit" value="Request8" name="request8" class="btn btn-default" />
                    </div>
                </td>
            </div>
        }
    </tr>
    <tr>
        @using (Html.BeginForm("Request9", "home", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            <div class="form-group">
                
                <td>
                    <div class="col-md-10">
                        <label for="request9">Show average comments count for each publication</label>
                    </div>
                </td>
                <td>
                    <div class="col-md-10">
                        <input type="submit" value="Request9" name="request9" class="btn btn-default" />
                    </div>
                </td>
                
            </div>
        }
    </tr>
    <tr>
        @using (Html.BeginForm("Request10", "home", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            <div class="form-group">
                
                <td>
                    <div class="col-md-10">
                        <label for="request10">Show users who has full activity</label>
                    </div>
                </td>
                <td>
                    <div class="col-md-10">
                        <input type="submit" value="Request10" name="request10" class="btn btn-default" />
                    </div>
                </td>
               
            </div>
        }
    </tr>
</table>